---
output: html_document
editor_options: 
  chunk_output_type: console
---
Lesson 3
==============================================================================

## Set working directory
```{r}
setwd("C:/Users/clu73519/Repos/Udacity/Exploratory_Data_Analysis/Explore_One_Variable")
```


## Read in Data
```{r}
getwd()
list.files()
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')
names(pf)
```

## Histgram of User's birthdays
```{r}
# install.packages('ggplot2')
library(ggplot2)

# install.packages('ggthemes', dependencies = TRUE)
library(ggthemes)

theme_set(theme_minimal(16))

names(pf)
qplot(data = pf, x = dob_day) +
  scale_x_continuous(breaks = 1:31)

```

## Faceting
```{r}
qplot(data = pf, x = dob_day) +
  scale_x_continuous(breaks = 1:31) +
  facet_wrap(~dob_month, ncol = 3)

```

## Friend Count
```{r}
# plot the friend count data
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')
qplot(data = pf, x = friend_count)

# this is the alternate method using ggplot() instead of qplot()
ggplot(data = pf, aes(x = friend_count)) + 
  geom_histogram()

```

## Limiting the axes
```{r}
qplot(data = pf, x = friend_count, xlim = c(0, 1000))

# aleternate solution 1
qplot(data = pf, x = friend_count) +
  scale_x_continuous(limits = c(0, 1000))

# alternate solution 2
ggplot(data = pf, aes(x = friend_count)) +
  geom_histogram() +
  scale_x_continuous(limits = c(0, 1000))
```

## Adjusting bin Width
```{r}
ggplot(data = pf, aes(x = friend_count)) +
  geom_histogram(binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0,1000,50)) +
  
  facet_wrap(~gender, ncol = 3)
```

## Ommitting NA observations
```{r}
ggplot(data = subset(pf, !is.na(gender)), aes(x = friend_count)) +
  geom_histogram(binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0,1000,50)) +
  
  facet_wrap(~gender, ncol = 3)
```

## Statistics 'by' gender
```{r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
```


## Investiagting Tenure (how long a user has been on FB) - Using colors to make plots pretty
```{r}
ggplot(data = pf, aes(x = tenure/365)) +
  geom_histogram(binwidth = 0.5, color = 'black', fill = 'blue')
```

## Labelling Plots
```{r}
ggplot(data = pf, aes(x = tenure/365)) +
  geom_histogram(binwidth = 0.25, color = 'black', fill = 'blue') +
  scale_x_continuous(breaks = seq(1,7,1), limits =c(0,7)) +
  xlab('Number of years using Facebook') +
  ylab('Number of users in sample')
```

## User Ages
```{r}
ggplot(data = pf, aes(x = age)) +
  geom_histogram(binwidth = 1, color = 'black', fill = 'orange') +
  scale_x_continuous(breaks = seq(0,113,5), limits = c(0,120)) +
  xlab('User Age') +
  ylab('Number of users in sample')
```

## Transforming Data
```{r}
# install.packages('gridExtra')
library(gridExtra)


```
